version: '3.4'


services:
  database:
    image: postgres:11-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    logging:
      driver: none

  pgbouncer:
    image: pgbouncer/pgbouncer
    ports:
      - 6432:6432
    env_file: .env.prod

  backend:
    tty: true
    build:
      context: ./backend
      target: dev
    env_file: .env.prod
    volumes:
      - ./backend/cw:/app/cw
      # - ./backend/alembic:/app/alembic
      - ./backend/development.ini:/app/development.ini
      - ./files:/app/files

  celery_worker:
    image: "${PROJECT_NAME}-backend"
    command: celery -A cw.celery worker --loglevel=info --autoscale=1
    env_file: .env.prod
    depends_on:
      - backend
    links:
      - backend
      - redis

  nginx:
    build:
      context: ./nginx
      target: dev
    ports:
      - "80:8000"
      - "443:443"
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - backend
    volumes:
      # - ./nginx/dev/html/index.html:/home/html/index.html:ro
      - ./files:/home/files:ro
      - /home/ubuntu/certbot/www:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
#      - frontend-admin-dist:/home/html:ro
      - frontend-client-dist:/home/html:ro
      - /etc/letsencrypt/live/certs/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/certs/privkey.pem:/certs/privkey.pem:ro


  frontend_client:
    tty: true
    build:
      context: ./frontend_client
      target: prod
    volumes:
      - frontend-client-dist:/frontend_client:rw
    ports:
      - "3001:3000"
    env_file: .env.dev

#  frontend_admin:
#    tty: true
#    build:
#      context: ./frontend_admin
#      target: prod
#    volumes:
#      - frontend-admin-dist:/frontend-dist:rw
#    ports:
#      - "3002:3000"
#    env_file: .env.dev
