"""_

Revision ID: a65c77cbbd6e
Revises: 1c4670d79a85
Create Date: 2022-04-25 13:17:06.095048

"""

# revision identifiers, used by Alembic.
revision = 'a65c77cbbd6e'
down_revision = '1c4670d79a85'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
