"""_

Revision ID: cf7690d98e29
Revises: ee9699eeb338
Create Date: 2022-04-25 17:43:37.126793

"""

# revision identifiers, used by Alembic.
revision = 'cf7690d98e29'
down_revision = 'ee9699eeb338'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test_type_id', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('test', 'test_id')
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('test', 'user_id')
    op.drop_column('test', 'test_type_id')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
