"""add_test_table_

Revision ID: ee9699eeb338
Revises: 1c4670d79a85
Create Date: 2022-04-25 14:57:16.970480

"""

# revision identifiers, used by Alembic.
revision = 'ee9699eeb338'
down_revision = '1c4670d79a85'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('tests', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tests')
    op.drop_table('test')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
