"""add_created_at_for_Test_

Revision ID: 4a10a37e04fd
Revises: 412aa0c74b8f
Create Date: 2022-04-26 13:16:06.549868

"""

# revision identifiers, used by Alembic.
revision = '4a10a37e04fd'
down_revision = '412aa0c74b8f'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'created_at')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
