"""add_anamnesisFromPsychologist_

Revision ID: 412aa0c74b8f
Revises: cf7690d98e29
Create Date: 2022-04-25 20:31:19.668608

"""

# revision identifiers, used by Alembic.
revision = '412aa0c74b8f'
down_revision = 'cf7690d98e29'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('anamnesisFromPsychologist', sa.String(), nullable=True))
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'anamnesisFromPsychologist')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
