"""Add_created_by_field_to_Test_

Revision ID: 30bfaaffd30c
Revises: 1448c4784396
Create Date: 2023-06-13 19:02:17.844154

"""

# revision identifiers, used by Alembic.
revision = '30bfaaffd30c'
down_revision = '1448c4784396'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('created_by', sa.Integer(), nullable=True))
    test = sa.table('test',
                    sa.Column('id', sa.Integer()),
                    sa.Column('created_by', sa.Integer()),
                    )
    op.execute(
        test.update().where(test.c.created_by == None).values({ "created_by": 1 })
    )

    op.alter_column('test', 'created_by', nullable=False)

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'created_by')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
