"""increase_question_category.description_max_length_

Revision ID: 5ca786fcaf1e
Revises: def3b7ac4b92
Create Date: 2023-06-06 21:51:45.502094

"""

# revision identifiers, used by Alembic.
revision = '5ca786fcaf1e'
down_revision = 'def3b7ac4b92'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_category', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_category', 'description',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
