"""Remade_Test_model_to_CompletedTest_

Revision ID: 2544630a174f
Revises: 4a10a37e04fd
Create Date: 2023-05-20 21:25:06.248760

"""

# revision identifiers, used by Alembic.
revision = '2544630a174f'
down_revision = '4a10a37e04fd'

from alembic import op, context
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###

def schema_downgrades():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('completed_tests')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
