"""Corrected_Category_and_ResulGrade_models._

Revision ID: 7b6790de1508
Revises: 0cffc0b6a3ae
Create Date: 2023-05-21 15:14:05.169430

"""

# revision identifiers, used by Alembic.
revision = '7b6790de1508'
down_revision = '0cffc0b6a3ae'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_category_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('grade')
    op.add_column('result_category', sa.Column('description', sa.String(length=1024), nullable=False))
    op.add_column('result_category', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_column('result_category', 'category_name')
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_category', sa.Column('category_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('result_category', 'name')
    op.drop_column('result_category', 'description')
    op.create_table('grade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_category.id'], name='grade_result_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grade_pkey')
    )
    op.drop_table('result_grade')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
