"""Add_test_id_field_to_ResultOption_

Revision ID: def3b7ac4b92
Revises: 0dc35747c15f
Create Date: 2023-06-02 14:14:34.493962

"""

# revision identifiers, used by Alembic.
revision = 'def3b7ac4b92'
down_revision = '0dc35747c15f'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_option', sa.Column('test_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'result_option', 'test', ['test_id'], ['id'])
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result_option', type_='foreignkey')
    op.drop_column('result_option', 'test_id')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
