"""added_sequential_number_for_question_

Revision ID: 143d661aa7ee
Revises: 7b6790de1508
Create Date: 2023-05-23 12:01:42.355025

"""

# revision identifiers, used by Alembic.
revision = '143d661aa7ee'
down_revision = '7b6790de1508'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # Set default values for 'service' column
    op.add_column('question', sa.Column('sequential_number', sa.Integer(), nullable=True))

    question = sa.table('question',
                     sa.Column('id', sa.Integer()),
                     sa.Column('sequential_number', sa.Integer()),
                     )
    op.execute(
        question.update().where(question.c.sequential_number == None).values({ "sequential_number": 1 })
    )

    op.alter_column('question', 'sequential_number', nullable=False)

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'sequential_number')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
