"""add_note_for_testing_

Revision ID: 10430028df65
Revises: 30bfaaffd30c
Create Date: 2023-06-20 19:49:42.987041

"""

# revision identifiers, used by Alembic.
revision = '10430028df65'
down_revision = '30bfaaffd30c'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testing', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testing', 'note')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
