"""Add_activ_field_to_Test_

Revision ID: 1448c4784396
Revises: e99c3cb120e9
Create Date: 2023-06-13 15:59:52.282415

"""

# revision identifiers, used by Alembic.
revision = '1448c4784396'
down_revision = 'e99c3cb120e9'

from alembic import op, context
import sqlalchemy as sa



def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('activ', sa.Boolean(), nullable=True))
    test = sa.table('test',
                        sa.Column('id', sa.Integer()),
                        sa.Column('activ', sa.Integer()),
                        )
    op.execute(
        test.update().where(test.c.activ == None).values({ "activ": False })
    )

    op.alter_column('test', 'activ', nullable=False)

def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'activ')
    # ### end Alembic commands ###

def data_upgrades():
    pass

def data_downgrades():
    pass
